### ISSUE TITLE
Donate link on README.md points to page not found

### ISSUE THREAD

**Issue by jbollman7** [wordnik/wordlist#1]
**Expected Behavior**
When clicking on the  bitly url link `bit.ly/donatenik` I expected to be taken to a page that i can donate to.

**Actual Behavior**
Github page 404, page not found

**Comment by emckean** [comment]
thanks for finding this! Should be fixed now. 
We'd love to send you some Wordnik stickers for helping us improve this repo; if you'd like some, just email us at feedback at wordnik.com with a mailing address!

**Comment by jbollman7** [comment]
Food for thought, would you ever consider using paypal, or another third party payment service for donations?

**Comment by emckean** [comment]
Thank you! Since we're a tiny nonprofit with limited engineering resources, we don't have accepting other payment services on our roadmap at the moment.
