### ISSUE TITLE
Unknown words

### ISSUE THREAD

**Issue by Lilja** [wordnik/wordlist#3]
I tried to find any sort of definition but couldn't. Are these correct English words?

aarti
dalt
appair

**Comment by emckean** [comment]
aarti: http://wordnik.com/words/aarti
dalt: https://www.wordnik.com/words/dalt
appair: https://www.wordnik.com/words/appair

**Comment by Lilja** [comment]
Thanks! I looked at merriam-webster for these definitions. I guess there's quite a divergence when it comes to word definitions.

**Comment by emckean** [comment]
Wordnik's goal is to have information about every word in English, so we are a bit bigger than some other online dictionaries. :)
