### ISSUE TITLE
Nested list parsing

### ISSUE THREAD

**Issue by dr460r** [wordnik/wordlist#5]
Hi, this isn't word suggestion but possible mistake in parsing definitions from sources, so I'm not sure if I'm supposed to write this as an Issue, but anyway.

When definition has "especially" at the end, and then sub-list of definitions, they come as separate on Wordnik.

**Example**  
On Wordnik  
![image](https://user-images.githubusercontent.com/62907395/179520927-97fd3e21-ffda-4547-8a50-f3a5e02aa7fe.png)
On AH Dictionary  
![image](https://user-images.githubusercontent.com/62907395/179521061-b7a21b89-e51f-4660-935a-0caa321bbcd2.png)

Maybe this is known/intentional behavior, but it looked strange to me when I saw just "especially" and full stop :)

**Comment by emckean** [comment]
hi! I'm closing this here because it's not a wordlist issue, but I appreciate the bug report! if you want to email us at feedbackATwordnik.com with a mailing address we'd be happy to send you some Wordnik stickers!
