### ISSUE TITLE
_NOTE: the Wordnik wordlist does not include proper names, acronyms or abbreviations, or phrases._

### ISSUE THREAD

**Issue by jaderaejackson** [wordnik/wordlist#7]
_NOTE: the Wordnik wordlist does not include proper names, acronyms or abbreviations, or phrases._

### Add one word per line. Use {} to enclose any comments.

(_example word—remove before committing_)

splendiferazing {blend of splendiferous and amazing}

_Originally posted by @jaderaejackson in https://github.com/wordnik/wordlist/issues/6_

**Comment by emckean** [comment]
Hi! This is a great word, but it's not standardized enough to include in our games wordlist. I suggest you leave a comment defining it here, instead: https://www.wordnik.com/words/splendiferazing#discuss
